//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplification.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double arenda_textBox {
            get {
                return ((double)(this["arenda_textBox"]));
            }
            set {
                this["arenda_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double svet_tarif_textBox {
            get {
                return ((double)(this["svet_tarif_textBox"]));
            }
            set {
                this["svet_tarif_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double svet_t_textBox {
            get {
                return ((double)(this["svet_t_textBox"]));
            }
            set {
                this["svet_t_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double svet_n_textBox {
            get {
                return ((double)(this["svet_n_textBox"]));
            }
            set {
                this["svet_n_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double voda_cena_textBox {
            get {
                return ((double)(this["voda_cena_textBox"]));
            }
            set {
                this["voda_cena_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double voda_t_textBox {
            get {
                return ((double)(this["voda_t_textBox"]));
            }
            set {
                this["voda_t_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double voda_n_textBox {
            get {
                return ((double)(this["voda_n_textBox"]));
            }
            set {
                this["voda_n_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double musor_textBox {
            get {
                return ((double)(this["musor_textBox"]));
            }
            set {
                this["musor_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double prir_gas_cena_textBox {
            get {
                return ((double)(this["prir_gas_cena_textBox"]));
            }
            set {
                this["prir_gas_cena_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double raspr_prir_gas_textBox {
            get {
                return ((double)(this["raspr_prir_gas_textBox"]));
            }
            set {
                this["raspr_prir_gas_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double prir_gas_t_textBox {
            get {
                return ((double)(this["prir_gas_t_textBox"]));
            }
            set {
                this["prir_gas_t_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double prir_gas_n_textBox {
            get {
                return ((double)(this["prir_gas_n_textBox"]));
            }
            set {
                this["prir_gas_n_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double voda_abonplata_textBox {
            get {
                return ((double)(this["voda_abonplata_textBox"]));
            }
            set {
                this["voda_abonplata_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double voda_otvod_textBox {
            get {
                return ((double)(this["voda_otvod_textBox"]));
            }
            set {
                this["voda_otvod_textBox"] = value;
            }
        }
    }
}
