//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplification.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string arenda_textBox {
            get {
                return ((string)(this["arenda_textBox"]));
            }
            set {
                this["arenda_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string svet_tarif_textBox {
            get {
                return ((string)(this["svet_tarif_textBox"]));
            }
            set {
                this["svet_tarif_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string svet_t_textBox {
            get {
                return ((string)(this["svet_t_textBox"]));
            }
            set {
                this["svet_t_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string svet_n_textBox {
            get {
                return ((string)(this["svet_n_textBox"]));
            }
            set {
                this["svet_n_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string voda_cena_textBox {
            get {
                return ((string)(this["voda_cena_textBox"]));
            }
            set {
                this["voda_cena_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string voda_t_textBox {
            get {
                return ((string)(this["voda_t_textBox"]));
            }
            set {
                this["voda_t_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string voda_n_textBox {
            get {
                return ((string)(this["voda_n_textBox"]));
            }
            set {
                this["voda_n_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string obsl_textBox {
            get {
                return ((string)(this["obsl_textBox"]));
            }
            set {
                this["obsl_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string musor_textBox {
            get {
                return ((string)(this["musor_textBox"]));
            }
            set {
                this["musor_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prir_gas_textBox {
            get {
                return ((string)(this["prir_gas_textBox"]));
            }
            set {
                this["prir_gas_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string raspr_prir_gas_textBox {
            get {
                return ((string)(this["raspr_prir_gas_textBox"]));
            }
            set {
                this["raspr_prir_gas_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string otoplenie_abonplata_textBox {
            get {
                return ((string)(this["otoplenie_abonplata_textBox"]));
            }
            set {
                this["otoplenie_abonplata_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string otoplenie_textBox {
            get {
                return ((string)(this["otoplenie_textBox"]));
            }
            set {
                this["otoplenie_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string voda_abonplata_textBox {
            get {
                return ((string)(this["voda_abonplata_textBox"]));
            }
            set {
                this["voda_abonplata_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string arenda_2_textBox {
            get {
                return ((string)(this["arenda_2_textBox"]));
            }
            set {
                this["arenda_2_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string svet_tarif_2_textBox {
            get {
                return ((string)(this["svet_tarif_2_textBox"]));
            }
            set {
                this["svet_tarif_2_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string svet_t_2_textBox {
            get {
                return ((string)(this["svet_t_2_textBox"]));
            }
            set {
                this["svet_t_2_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string svet_n_2_textBox {
            get {
                return ((string)(this["svet_n_2_textBox"]));
            }
            set {
                this["svet_n_2_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string voda_textBox {
            get {
                return ((string)(this["voda_textBox"]));
            }
            set {
                this["voda_textBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string signal_textBox {
            get {
                return ((string)(this["signal_textBox"]));
            }
            set {
                this["signal_textBox"] = value;
            }
        }
    }
}
